### ISSUE TITLE
question on polygon as type1 zkevm

### ISSUE THREAD

**Issue by NOOMA-42** [LimeChain/RollupCodes#80]
As Polygon official blog state they've already become type1 zkevm. Does the doc could potentially update?
[Link](https://polygon.technology/blog/upgrade-every-evm-chain-to-zk-introducing-the-type-1-prover)

**Comment by Daniel-K-Ivanov** [comment]
@NOOMA-42 the type1 zkevm is an additional operating mode to their prover, however the actual Polygon zkEVM itself is not running in that mode at the moment, so technically the Polygon zkEVM is not type1 compatible.

This can be observed by looking at the differences compared to L1. f.e the precompiles
