### ISSUE TITLE
zkSync Era - Timestamp, block number, and block hash now give values for the L2 block.

### ISSUE THREAD

**Issue by adamegyed** [LimeChain/RollupCodes#81]
Per this network upgrade: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/87

It seems like the opcodes `number`, `blockhash`, and `timestamp` return values for the L2 block, rather than the L1 batch block.

There may be other changes related to this as well, including new functions of system contracts.

**Comment by Daniel-K-Ivanov** [comment]
Thanks for the issue. We have started the reevaluation and content updates for all rollups. From now on they will be regularly updated.
